'use client';
import { useState, useTransition } from 'react';
import { Info } from 'lucide-react';
type Curso = { id:string; title:string; subtitle:string|null; cover_image_url:string|null; liberado:boolean };
export default function AcessoCursosClient({profileId,nome,cursos}:{profileId:string;nome:string;cursos:Curso[]}) {
 const [selecionados,setSelecionados]=useState(()=>new Set(cursos.filter(c=>c.liberado).map(c=>c.id))); const [mensagem,setMensagem]=useState(''); const [isPending,startTransition]=useTransition();
 function alternar(id:string){setSelecionados(atual=>{const proximo=new Set(atual);proximo.has(id)?proximo.delete(id):proximo.add(id);return proximo;});}
 function salvar(){setMensagem('');startTransition(async()=>{const resposta=await fetch('/api/admin/usuarios/acessos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profileId,courseIds:Array.from(selecionados)})});const dados=await resposta.json().catch(()=>({}));setMensagem(resposta.ok?'Acessos salvos com sucesso.':dados.error||'Não foi possível salvar os acessos.');});}
 return <><div className="acc-head"><div><h2>Liberar acesso aos cursos</h2><p>Ligue o acesso de cada curso. Só os cursos ligados aparecem para esta aluna.</p></div><div className="bulk"><button className="btn-ghost" onClick={()=>setSelecionados(new Set(cursos.map(c=>c.id)))}>Liberar todos</button><button className="btn-ghost" onClick={()=>setSelecionados(new Set())}>Bloquear todos</button></div></div>
 <div className="courses">{cursos.length===0?<div style={{padding:24}}>Nenhum curso cadastrado.</div>:cursos.map(c=>{const on=selecionados.has(c.id);return <div className="crow" key={c.id}><div className="thumb t-pk" style={c.cover_image_url?{backgroundImage:`url(${c.cover_image_url})`,backgroundSize:'cover',backgroundPosition:'center'}:undefined}><span>{c.title}</span></div><div className="info"><h3>{c.title}</h3><small>{c.subtitle||'Curso da Academia'}</small></div><span className={`state ${on?'lib':'blo'}`}>{on?'Liberado':'Bloqueado'}</span><button type="button" aria-label={`${on?'Bloquear':'Liberar'} ${c.title}`} className={`toggle ${on?'on':'off'}`} onClick={()=>alternar(c.id)}/></div>;})}</div>
 <div className="foot"><div><div className="summary"><b>{selecionados.size}</b> de <b>{cursos.length}</b> cursos liberados para {nome}</div>{mensagem&&<small className="save-message">{mensagem}</small>}</div><button className="btn-pink-sq" disabled={isPending} onClick={salvar}>{isPending?'Salvando...':'Salvar acessos'}</button></div><div className="ac-note"><Info size={16}/>Quando a compra vem pelo checkout, o acesso é liberado automaticamente. Esta tela serve para cortesia, suporte, venda externa ou reembolso.</div></>;
}
